version: '3'
services:
  node:
    container_name: node
    restart: always
    build:
      context: ./node
    volumes:
      - ./node:/app
    ports:
      - '3000:3000'
    entrypoint: wait-for db:3306 -t 40 -- docker-entrypoint.sh
    depends_on:
      - db
    networks:
      - app-network

  nginx:
    build:
      context: ./nginx
    container_name: nginx
    restart: always
    ports:
      - '8080:80'
    networks:
      - app-network

  db:
    build: 
      context: ./mysql
    container_name: db
    restart: always
    tty: true
    networks:
      - app-network
    volumes:
      - ./mysql/volume:/var/lib/mysql:rw
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root

networks:
  app-network:
    driver: bridge