version: '3'
services:
  node:
    container_name: node
    restart: always
    build:
      context: ./node
    ports:
      - '3000:3000'
    networks:
      - app-network

  nginx:
    build:
      context: ./nginx
    container_name: nginx
    restart: always
    ports:
      - '8080:80'
    networks:
      - app-network

networks:
  app-network:
    driver: bridge